repos:
  # Basic file hygiene and validation.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Linting and formatting.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  # Type checking.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: ["app"]
        pass_filenames: false
        additional_dependencies:
          - pydantic==2.12.5
          - pydantic-settings==2.12.0
